services:
  qdrant-db:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - 6333:6333
    environment:
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - ./qdrant-data:/qdrant/storage
  redis-db:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data